### PR TITLE
Sanity checks for vector length

### PR DESCRIPTION
**Pull request by neosilky**
Found a couple of panics using `cargo-fuzz` which are fixed by the following changes.

### CODE REVIEW

**Comment by apoelstra** [comment]
Cool, thanks! Can you also commit the fuzzing support code?

**Comment by neosilky** [comment]
Hi @apoelstra! I've added the fuzzing code - there are a few things to fuzz so I've tried to make it as simple as possible.

**Comment by Kixunil** [comment]
@neosilky Is there some online corpus of blockchain data?

**Comment by neosilky** [comment]
@Kixunil I'm not actually sure. I just let `cargo-fuzz` run and generate its own corpus.

**Comment by apoelstra** [comment]
Great, thanks!

**Comment by apoelstra** [comment]
ACK

**Comment by Kixunil** [comment]
@neosilky AFAIK using corpus based on existing known good data is very efficient. I've read somewhere that Google is building large corpus of different file formats etc.

I'd be nice to do this for Bitcoin too.

**Pull request merged**
