### PR TITLE
Remove some dependencies; bump major version number

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by apoelstra** [comment]
cc @TheBlueMatt ; I didn't realize that using `num` like this was forcing all downstream users of the bignum types to also pull in `num`.

**Comment by apoelstra** [comment]
Reduces the total build dependency list to 22 crates from 51. The remaining ones come from `serde` and `strason`, which in general need to be cleaned up. I may just feature-gate them at some point but it would be nice to also update `serde` and get rid of `strason` at the same time...but currently this is impossible, see https://github.com/serde-rs/serde/issues/185

**Comment by apoelstra** [comment]
Updated to add `serde` dependency to secp256k1, since (a) we already have this dependency at the top level (for now), and (b) I believe we need this for Liquid.

**Comment by TheBlueMatt** [comment]
Tested, my stuff still compiles/passes tests, didn't review the backport of the jsonrpc/serde macros at all but looked over everything else.

**Comment by apoelstra** [comment]
Great, thanks!

**Pull request merged**
